- hosts: localhost
  vars:
    gcp_region: europe-west4
    gcp_zone: europe-west4-a
    gcp_project: glassy-mystery-232515
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../../credentials.json
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20190514 
  roles:
    #create network
    - role: gcp-network

    #create spark master
    - role: gcp-instance
      vars:
        gcp_machine_type: n1-highcpu-8
        instances:
          - { index: 1, tag: spark-master }
        disk_size: 50
        disk_type: pd-standard
        type: spark-master
        external_ip: true
    
    #create spark slaves
    - role: gcp-instance
      vars:
        gcp_machine_type: n1-highcpu-8
        instances:
          - { index: 1, tag: spark-slave }
          - { index: 2, tag: spark-slave }
        disk_size: 50
        disk_type: pd-standard
        type: spark-slave
        external_ip: true

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for instances to respond
      wait_for:
        host: "{{ item }}"
        port: 22
      loop: "{{ groups['all'] }}"
    

- hosts: all
  become: yes
  tasks:
    - name: Wait for updates to finish
      shell: while pgrep apt; do sleep 10; done;
    - debug:
        var: groups
    - debug:
        var: groups['spark-master']
    - debug:
        var: groups['spark-master'][0]

- hosts: spark-master
  become: yes
  roles:
    - { role: master }

- hosts: spark-slave
  become: yes
  roles:
    - { role: slave }


