# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageReference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageReference.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\010protobufB\023ImageReferenceProto'),
  serialized_pb=_b('\n\x14ImageReference.proto\"#\n\x0eImageReference\x12\x11\n\treference\x18\x01 \x02(\tB\x1f\n\x08protobufB\x13ImageReferenceProto')
)




_IMAGEREFERENCE = _descriptor.Descriptor(
  name='ImageReference',
  full_name='ImageReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference', full_name='ImageReference.reference', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['ImageReference'] = _IMAGEREFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageReference = _reflection.GeneratedProtocolMessageType('ImageReference', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREFERENCE,
  __module__ = 'ImageReference_pb2'
  # @@protoc_insertion_point(class_scope:ImageReference)
  ))
_sym_db.RegisterMessage(ImageReference)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
